services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    env_file:
      - ../../global.env
    environment:
      - LIBVA_DRIVER_NAME=iHD
    ports:
      - "127.0.0.1:8096:8096" # HTTP
      # JELLYFIN_PublishedServerUrl: http://jellyfin.local
    user: "${USER_UID}:${USER_GID}"
    group_add:
      - "992" # render group for GPU access
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /mnt/media:/media:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
