services:
  nginx:
    image: nginx:alpine
    container_name: revproxy
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    env_file:
      - ../global.env
    # allow binding to :80 and :443 as non-root
    #cap_add:
    #  - NET_BIND_SERVICE
    #user: "${USER_UID}:${USER_GID}"
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
    attachable: true

