services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    env_file:
      - ../global.env
    # allow binding to :53 as non-root
    cap_add:
      - NET_BIND_SERVICE
    user: "${USER_UID}:${USER_GID}"
    ports:
      # DNS (set DNS_BIND_IP to LAN IP when live)
      - "${DNS_BIND_IP:-127.0.0.1}:53:53/udp"
      - "${DNS_BIND_IP:-127.0.0.1}:53:53/tcp"
      - "127.0.0.1:8053:80/tcp"
      # Initial setup UI on 3000
      # - "127.0.0.1:3000:3000/tcp"
    volumes:
      - /srv/adguard/conf:/opt/adguardhome/conf
      - /srv/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
