services:
  homepage:
    image: nginx:alpine
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true