services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    env_file:
      - ../../global.env
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
    volumes:
      - /srv/servarr/prowlarr:/config
    networks:
      - proxy

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - proxy

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    env_file:
      - ../../global.env
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
    volumes:
      - /srv/servarr/lidarr:/config
      - /mnt/media/Music:/music:ro
    networks:
      proxy:
        ipv4_address: ${LIDARR_IP}

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file:
      - ../../global.env
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
    volumes:
      - /srv/servarr/radarr:/config
      - /mnt/media/Movies:/movies:ro
    networks:
      proxy:
        ipv4_address: ${RADARR_IP}

networks:
  proxy:
    external: true
