services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    restart: unless-stopped
    env_file:
      - ../global.env
    # Use host network for auto-discovery (mDNS, SSDP, UPnP)
    network_mode: host
    user: "${USER_UID}:${USER_GID}"
    volumes:
      - /srv/homeassistant/config:/config
    # healthcheck:
    #   test: ["CMD", "curl", "-fsS", "http://localhost:8123/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
